@baseUrl = http://localhost:5215/api/v1

###
POST {{baseUrl}}/student
Content-Type: application/json

{
    "Name" : "lolo",
    "Phone" : "098765",
    "Address" : "syria",
    "DepartmentId" : "b95d40fa-a79b-43a3-9e39-02bc5be8b664"
}


###
PUT {{baseUrl}}/student
Content-Type: application/json

{
    "Id" : "0A6A3280-77C2-47CA-938D-2037A2E84994",
    "Name" : "queue",
    "Phone" : "123456",
    "Address" : "Gaza",
    "DepartmentId" : "b95d40fa-a79b-43a3-9e39-02bc5be8b664"
}

###
GET {{baseUrl}}/student
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJTdWIiOiJjNTNlZjBjMy1hMmI5LTQxODktYjg3Zi01MDM5M2Q0NjA2ZWUiLCJVc2VyTmFtZSI6ImpvaG4iLCJFbWFpbCI6ImpvaG4uZG9lQGV4YW1wbGUuY29tIiwiZXhwIjoxNzYyNjAzMDkzLCJpc3MiOiJTY2hvb2xQcm9qZWN0IiwiYXVkIjoiYXVkaWVuY2UifQ.SS3a-zPhSKSc4muxxbJRTrVLxKnWT_YPpngPt4wpF44


###
GET {{baseUrl}}/student/pagination?PageNumber=1&pagesize=9&orderby=1&search=a

###
GET {{baseUrl}}/student/B95D40FA-A79B-43A3-9E39-02BC5BE8B664

###
DELETE {{baseUrl}}/student/B95D40FA-A79B-43A3-9E39-02BC5BE8B664


