
###
POST http://localhost:5215/api/v1/user
Content-Type: application/json

{
  "fullName": "John Doe",
  "email": "soubhy185@gmail.com",
  "userName": "sop",
  "country": "Hungary",
  "address": "123 Main Street, Szigetszentmiklós",
  "phoneNumber": "+36 30 123 4567",
  "password": "SecurePassword123!",
  "confirmPassword": "SecurePassword123!"
}

###
PUT http://localhost:5215/api/v1/user
Content-Type: application/json

{
  "id": "c53ef0c3-a2b9-4189-b87f-50393d4606ee",
  "fullName": "Doe",
  "email": "john.doe@example.com",
  "userName": "john",
  "country": "Hu",
  "address": "123 Main Street",
  "phoneNumber": "036 30 123 4567"
}

###
DELETE http://localhost:5215/api/v1/user/3edf1272-251f-4ade-8e06-60016e03a78d

###
PUT http://localhost:5215/api/v1/user/change-password
Content-Type: application/json

{
  "id": "c53ef0c3-a2b9-4189-b87f-50393d4606ee",
  "oldpassword" : "SecurePassword123!",
  "newpassword" : "Koko12@s",
  "confirmedpassword" : "Koko12@s"
}

###
POST http://localhost:5215/api/v1/authentication/signin
Content-Type: application/json

{
    "UserName" : "Admin",
    "Password" : "Admin1234@"
}


###
POST http://localhost:5215/api/v1/authentication/refresh-token
Content-Type: application/json

{
    "accessToken" : "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJTdWIiOiJjNTNlZjBjMy1hMmI5LTQxODktYjg3Zi01MDM5M2Q0NjA2ZWUiLCJVc2VyTmFtZSI6ImpvaG4iLCJFbWFpbCI6ImpvaG4uZG9lQGV4YW1wbGUuY29tIiwiZXhwIjoxNzYyNzU5ODE4LCJpc3MiOiJTY2hvb2xQcm9qZWN0IiwiYXVkIjoiYXVkaWVuY2UifQ.BNMErj1F8AaSa2RyNQD71G8lkMk7qol8IxV-2YISIC8",
    "refreshToken" : "Tiudv2Qr3tcil4ib0qbg0OUrBFgyP8aQTpXj8k/ouGAKTUioFRqChxpj5WcVjSt1y15OCG+2xCW3UgPZZ3X7UQ=="
}
###
GET http://localhost:5215/api/v1/student/pagination?PageNumber=1&pagesize=9&orderby=1&search=l
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJTdWIiOiJjNTNlZjBjMy1hMmI5LTQxODktYjg3Zi01MDM5M2Q0NjA2ZWUiLCJVc2VyTmFtZSI6ImpvaG4iLCJFbWFpbCI6ImpvaG4uZG9lQGV4YW1wbGUuY29tIiwiZXhwIjoxNzYyNjkwNjcxLCJpc3MiOiJTY2hvb2xQcm9qZWN0IiwiYXVkIjoiYXVkaWVuY2UifQ.ZwRrL1JvGB5AEEhZqnKLtKt9AAghRBXboQrVAplRz_E

###
POST http://localhost:5215/api/v1/authorization
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJTdWIiOiJjNTNlZjBjMy1hMmI5LTQxODktYjg3Zi01MDM5M2Q0NjA2ZWUiLCJVc2VyTmFtZSI6ImpvaG4iLCJFbWFpbCI6ImpvaG4uZG9lQGV4YW1wbGUuY29tIiwiZXhwIjoxNzYyNzYxOTUyLCJpc3MiOiJTY2hvb2xQcm9qZWN0IiwiYXVkIjoiYXVkaWVuY2UifQ.c3eZiagOoqPQyVNT8kAFFB37u5r9w_9nx9i4wbAhmWk

{
    "roleName" : ""
}

###
POST http://localhost:5215/api/v1/Email/send-email
Content-Type: application/json

{
    "email" : "soubhy185@gmail.com",
    "message" : "https://www.youtube.com"
}

###
POST http://localhost:5215/api/v1/authentication/confirm-email-ByCode?userId=c0b98884-1976-4c5a-94cf-a648a9cfaf7a&code=CfDJ8AxqxJPC52RLksVp8NZXM4yeSxAlAsMWQA7S4F0pjPMDmiSNd8asbKrK9caDr+nMJMfTt/F5sb3Um9JZt4rWWToPBtIzJNdxeSPQwxOrhBhV02rt+cXKjeu3+IlMV+s3vEaRKs9ngSqMPwLlvClK4mzuuOSVn5fzSJc69+n7FyEH1ish1eq35sXLvwc8+/vzQzw7ghNjEWS+nKLLzkEys80+UeAbOfquJAOg8/8Lb6Z8GYnsWAFaYQSsCdcEu3z2fA==
Content-Type: application/json



###
POST http://localhost:5215/api/v1/authentication/code-email-confirm/e5437778-9c9e-4102-ab25-471d67728481
